var WarpShader = [
    "varying vec2 textureCoordinate;",
    "",
    "uniform sampler2D inputImageTexture;",
    "uniform sampler2D inputImageTexture2;",
    "",
    "uniform float multiplier;",
    "",
    "void main() {",
    "    vec2 xy = textureCoordinate.xy;",
    "",
    "    vec4 noise = texture2D(inputImageTexture2, xy);",
    "",
    "    vec2 diff = noise.xy - .5;",
    "    diff *= multiplier;",
    "",
    "    vec2 coords = xy + diff;",
    "",
    "    vec4 color = texture2D(inputImageTexture, xy + diff);",
    "    //vec4 color = texture2D(inputImageTexture2, textureCoordinate);",
    "",
    "    if (coords.x > 1.0 || coords.x < 0.0 || coords.y > 1.0 || coords.y < 0.0) {",
    "        color = vec4(0.0, 0.0, 0.0, 0.0);",
    "    }",
    "",
    "    gl_FragColor = color;",
    "}",
    ""
].join('\n');